name: docs-site
on:
  release:
    types: [ published ]
  # TODO: remove this before merge!
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          set -x
          export POLYNOTE_VERSION=$(git describe --tags)
          echo "Docs Site Build ${POLYNOTE_VERSION}"
          git config --global user.email "polynote-ci@polynote.org"
          git config --global user.name "Polynote CI"
          pushd $GITHUB_WORKSPACE/docs-site
            pip install -r requirements.txt
            mike deploy --push --update-aliases ${POLYNOTE_VERSION} latest
            mike set-default --push latest
          popd


