name: docs-site
on:
  push:
    branches:
      - master
      - main
  pull_request: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          echo "Docs Site Build"
          pushd $GITHUB_WORKSPACE/docs-site
            pip install -r requirements.txt
            mkdocs gh-deploy --force
          popd


